# -*- coding: utf-8 -*-
"""Exercise 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0WYLG-fd9hCjeu_3M7kJpXsrJ-AmIjH

### Exercise 1

Create a DataFrame with:

```
Name
Salary
Department
```

Add 5 employees.

---
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("PySpark Basics") \
    .getOrCreate()

print("Spark Session Created")

data = [
    ("Steve", 100000, "Development"),
    ("Jerry", 500000, "Development"),
    ("Bob", 10000, "Testing"),
    ("Alice", 20000, "Maintanence"),
    ("John", 3000000, "Business")
]

cols = ["Name", "Salary", "Department"]

df = spark.createDataFrame(data, cols)

df.show()

"""
### Exercise 2

Show only **Name and Salary** columns.

---

"""

df.select("Name", "Salary").show()

"""### Exercise 3

Filter employees with **salary greater than 50000**.

---


"""

df.filter(df["Salary"] > 50000).show()

"""### Exercise 4

Count employees per department.

---


"""

df.groupby("Department").count().show()

"""### Exercise 5

Sort employees by salary.
"""

df.sort("Salary", ascending=False).show()