# -*- coding: utf-8 -*-
"""PySpark DataFrame Exercises Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtO3C61XXTfiWVhimXigeSWaSULNJyLI

PySpark DataFrame Exercises Lab

Students will work with 4 datasets.
1. employees.csv
2. departments.csv
3. sales.csv
4. employees_nested.json

Dataset 1 — employees.csv

Students should create this file.

emp_id,name,department,salary,joining_date
1,Rahul,IT,70000,2023-01-10
2,Sneha,HR,60000,2022-11-15
3,Arjun,IT,75000,2023-03-01
4,Priya,Finance,80000,2022-12-20
5,Karan,IT,50000,2023-02-05
6,Meera,,72000,2023-04-10
7,Amit,HR,58000,2023-01-18

Dataset 2 — departments.csv

department,location
IT,Bangalore
HR,Mumbai
Finance,Delhi

Dataset 3 — sales.csv

sale_id,emp_id,product,amount
1,1,Laptop,75000
2,2,Mouse,1500
3,3,Keyboard,3000
4,1,Monitor,12000
5,4,Laptop,75000
6,3,Mouse,1000
7,5,Keyboard,1500
8,1,Laptop,75000

Dataset 4 — employees_nested.json

[
{
"emp_id":1,
"name":"Rahul",
"address":{"city":"Hyderabad","state":"Telangana"},
"skills":["Python","SQL"]
},
{
"emp_id":2,
"name":"Sneha",
"address":{"city":"Bangalore","state":"Karnataka"},
"skills":["HR","Recruitment"]
},
{
"emp_id":3,
"name":"Arjun",
"address":{"city":"Chennai","state":"Tamil Nadu"},
"skills":["PySpark","Azure","Python"]
}
]

PART 1 — DataFrame Creation

Load all datasets into PySpark DataFrames.
"""

from google.colab import files
uploaded = files.upload()

for i in uploaded.keys():
  print(i)

"""Exercise 1

Create a Spark session.
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder. \
appName("PySpark Exercise"). \
getOrCreate()

print("Spark session Created")

"""Exercise 2

Load employees.csv .
"""

employees = spark.read.csv("employees.csv", header=True, inferSchema=True)
employees.show()

"""Exercise 3

Load departments.csv .
"""

departments = spark.read.csv("departments.csv", header=True, inferSchema=True)
departments.show()

"""Exercise 4

Load sales.csv .
"""

sales = spark.read.csv("sales.csv", header=True, inferSchema=True)
sales.show()

"""Exercise 5

Load employees_nested.json .
"""

employees_nested = spark.read.option("multiLine", "true").json("employees_nested.json")
employees_nested.show()

"""Exercise 6

Print schema for all DataFrames.
"""

employees.printSchema()
departments.printSchema()
sales.printSchema()
employees_nested.printSchema()

"""PART 2 — Exploring Data

Exercise 7

Show first 5 rows of employees.
"""

employees.show(5)

"""Exercise 8

Count total employees.
"""

employees.count()

"""Exercise 9

List all column names.
"""

employees.columns

"""Exercise 10

Show only 3 rows.
"""

employees.head(3)

employees.show(3)

"""PART 3 — Selecting and Renaming

Exercise 11

Select only:
name
salary
"""

employees.select("name", "salary").show()

"""Exercise 12

Rename column salary to emp_salary .
"""

employees.withColumnRenamed("salary", "emp_salary").show()

"""
Exercise 13

Select employees who joined after 2023-01-01.
"""

employees.filter(employees.joining_date > "2023-01-01").show()

"""PART 4 — Filtering Data

Exercise 14

Find employees with salary greater than 65000.
"""

employees.filter(employees.salary > 65000).show()

"""Exercise 15

Find employees in IT department.
"""

employees.filter(employees.department == "IT").show()

"""
Exercise 16

Find employees in IT department with salary greater than 70000."""

employees.filter((employees.department == "IT") & (employees.salary > 70000)).show()

"""PART 5 — Dropping and Sorting

Exercise 17

Drop column joining_date .
"""

employees.drop("joining_date").show()

"""Exercise 18

Sort employees by salary ascending.
"""

employees.sort(employees.salary).show()

"""Exercise 19

Sort employees by salary descending.
"""

employees.sort(employees.salary, ascending=False).show()

"""Exercise 20

Find top 3 highest paid employees.
"""

employees.sort(employees.salary, ascending=False).show(3)

"""PART 6 — Aggregations"""

from pyspark.sql.functions import sum, avg, max, min

employees.select(
    sum("salary").alias("Total salary"),
    avg("salary").alias("Average salary"),
    max("salary").alias("Max salary"),
    min("salary").alias("Mins salary")
).show()

"""


Exercise 21

# Find total salary of all employees."""

employees.agg({"salary": "sum"}).show()

"""Exercise 22

Find average salary.
"""

employees.agg({"salary": "avg"}).show()

"""Exercise 23

Find highest salary.
"""

employees.agg({"salary": "max"}).show()

"""Exercise 24

Find lowest salary.
"""

employees.agg({"salary": "min"}).show()

"""PART 7 — GroupBy

Exercise 25

Count employees per department.
"""

employees.groupBy("department").count().show()

"""Exercise 26

Calculate average salary per department.

"""

employees.groupBy("department").agg({"salary": "avg"}).show()

"""Exercise 27

Find total salary per department.
"""

employees.groupBy("department").agg({"salary": "sum"}).show()

"""PART 8 — Joining DataFrames

Use employees.csv and departments.csv .

Exercise 28

Perform inner join.
"""

inner_join = employees.join(departments, employees.department == departments.department, "inner")
inner_join.show()

"""Exercise 29

Perform left join.
"""

left_join = employees.join(departments, employees.department == departments.department, "left")
left_join.show()

"""Exercise 30

Show employee name with department location.
"""

emp_dept = employees.join(departments, employees.department == departments.department, "inner")
emp_dept.select("name", "location").show()

"""PART 9 — Updating Data

Exercise 31

Add a column bonus = salary * 10%.
"""

updated_bonus = employees.withColumn("bonus", employees.salary * 0.1)
updated_bonus.show()

"""Exercise 32

Add a column company with value "BotCampus" .
"""

from pyspark.sql.functions import lit

emp_with_company = employees.withColumn("company", lit("BotCampus"))
emp_with_company.show()

"""PART 10 — Handling Null Values

Note employee Meera has null department.

Exercise 33

Find rows with null department.
"""

from pyspark.sql.functions import col

null_dept_df = employees.filter(col("department").isNull())

null_dept_df.show()

"""Exercise 34

Replace null department with "Unknown" .
"""

filled_emp = employees.fillna({"department": "Unassigned"})
filled_emp.show()

"""Exercise 35

Drop rows with null values.
"""

df_clean = employees.dropna()
df_clean.show()

"""PART 11 — Built-in Functions

Exercise 36

Convert employee names to uppercase.
"""

from pyspark.sql.functions import upper, col

df_upper = employees.withColumn("name", upper(col("name")))
df_upper.show()

"""Exercise 37

Find length of employee names.
"""

from pyspark.sql.functions import length, col

df_with_length = employees.withColumn("name_length", length(col("name")))
df_with_length.show()

"""Exercise 38

Create column salary_in_lakhs .
"""

from pyspark.sql.functions import col

df_with_lakhs = employees.withColumn("salary_in_lakhs", col("salary") / 100000)
df_with_lakhs.select("name", "salary", "salary_in_lakhs").show()

"""
PART 12 — When / Otherwise

Create salary category:
>= 75000 → High
60000–74999 → Medium
< 60000 → Low

Exercise 39

Create new column salary_grade ."""

from pyspark.sql.functions import col, when

df_graded = employees.withColumn(
    "salary_grade",
    when(col("salary") >= 75000, "High")
    .when(col("salary") >= 60000, "Medium")
    .otherwise("Low")
)

df_graded.select("name", "salary", "salary_grade").show()

"""PART 13 — Date Functions

Exercise 40

Convert joining_date to proper date format.
"""

from pyspark.sql.functions import to_date, col

employees.select("joining_date").show()
df_with_dates = employees.withColumn("joining_date", to_date(col("joining_date"), "yyyy-MM-dd"))

df_with_dates.show()

"""Exercise 41

Extract:

joining year   
joining month

"""

from pyspark.sql.functions import col, year, month

df_with_year = df_with_dates.withColumn("joining_year", year(col("joining_date")))

df_final = df_with_year.withColumn("joining_month", month(col("joining_date")))

df_final.select("name", "joining_date", "joining_year", "joining_month").show()

"""PART 14 — Union

Create another DataFrame with 2 new employees.

Exercise 42

Union the two DataFrames.
"""

from pyspark.sql import Row

new_data = [
    (8, "Vikram", "IT", 65000, "2023-05-12"),
    (9, "Sonia", "HR", 62000, "2023-06-01")
]

new_employees = spark.createDataFrame(new_data, ["emp_id", "name", "department", "salary", "joining_date"])

new_employees.show()

combined_df = employees.union(new_employees)

combined_df.show()

"""Exercise 43

Use unionByName
"""

from pyspark.sql import Row

new_data_shuffled = [
    ("Vikram", 8, "IT", 65000, "2023-05-12"),
    ("Sonia", 9, "HR", 62000, "2023-06-01")
]

new_employees_shuffled = spark.createDataFrame(
    new_data_shuffled,
    ["name", "emp_id", "department", "salary", "joining_date"]
)
combined_df = employees.unionByName(new_employees_shuffled)
combined_df.show()

"""PART 15 — Window Functions

Exercise 44

Rank employees by salary within department.
"""

from pyspark.sql.window import Window
from pyspark.sql.functions import rank, col

windowSpec = Window.partitionBy("department").orderBy(col("salary").desc())

df_ranked = employees.withColumn("rank", rank().over(windowSpec))

df_ranked.select("department", "name", "salary", "rank").show()

"""Exercise 45

Assign row number within department.
"""

from pyspark.sql.window import Window
from pyspark.sql.functions import row_number, col

windowSpec = Window.partitionBy("department").orderBy(col("salary").desc())

df_with_row_num = employees.withColumn("row_num", row_number().over(windowSpec))

df_with_row_num.select("department", "name", "salary", "row_num").show()

"""PART 16 — Working with Nested JSON

Exercise 46

Read employees_nested.json
"""

emp_nested = spark.read.option("multiLine", "true").json("employees_nested.json")

emp_nested.show()

"""Exercise 47

Extract:
emp_id
city
state
"""

from pyspark.sql.functions import col

# Extracting nested fields from 'address'
emp_address = emp_nested.select(
    col("emp_id"),
    col("address.city").alias("city"),
    col("address.state").alias("state")
)
emp_address.show()

"""Exercise 48

Explode the skills array.

Expected output example:

Rahul → Python

Rahul → SQL

"""

from pyspark.sql.functions import explode

# Flatten the skills array
emp_skills = emp_nested.select("name", explode(col("skills")).alias("skill"))
emp_skills.show()

"""PART 17 — Sales Analysis

Using sales.csv .

Exercise 49

Calculate total sales.
"""

from pyspark.sql.functions import sum

sales_df = spark.read.option("header", "true").option("inferSchema", "true").csv("sales.csv")
total_sales = sales_df.select(sum("amount")).collect()[0][0]
print(f"Total Sales: {total_sales}")

"""Exercise 50

Find total sales per employee.


"""

from pyspark.sql.functions import desc

# Grouping and finding the top performer
sales_per_emp = sales_df.groupBy("emp_id").agg(sum("amount").alias("total_emp_sales"))
sales_per_emp.show()

"""Exercise 51

Find best performing employee.


"""

best_emp = sales_per_emp.orderBy(desc("total_emp_sales")).limit(1)

best_emp.show()

"""Exercise 52

Find total sales per product.
"""

sales_df.groupBy("product").sum("amount").show()

"""
PART 18 — Applying Functions

Create a custom function that categorizes sales:
> 50000 → Premium
20000–50000 → Medium
< 20000 → Small

Exercise 53

Apply this function to create sale_category ."""

from pyspark.sql.functions import when

sales_df = sales_df.withColumn("sale_category",
    when(col("amount") > 50000, "Premium")
    .when(col("amount") >= 20000, "Medium")
    .otherwise("Small")
)
sales_df.show()

"""PART 19 — Pandas Comparison

Exercise 54

Convert Spark DataFrame to Pandas.
"""

import pandas as pd

pdf = employees.toPandas()

"""Exercise 55

Perform salary filtering using Pandas.
"""

filtered_pdf = pdf[pdf['salary'] > 65000]
print(filtered_pdf)

"""PART 20 — Widgets in Colab

Create widgets to filter employees.

Exercise 56

Create dropdown for department.
"""

import ipywidgets as widgets
from pyspark.sql.functions import col

# Get unique department names (removing nulls)
dept_list = sorted([row['department'] for row in employees.select("department").distinct().collect() if row['department']])

# Create the dropdown widget
dept_dropdown = widgets.Dropdown(
    options=dept_list,
    value=dept_list[0],
    description='Department:',
    style={'description_width': 'initial'}
)

display(dept_dropdown)

"""Exercise 57

Create slider for salary.
"""

salary_slider = widgets.IntSlider(
    value=50000,
    min=40000,
    max=100000,
    step=5000,
    description='Min Salary:',
    style={'description_width': 'initial'},
    continuous_update=False
)

display(salary_slider)

"""Exercise 58

Display employees based on widget values.
"""

from IPython.display import display, clear_output

def filter_employees(dept, min_salary):
    print(f"--- Results for {dept} with Salary >= {min_salary} ---")

    filtered_df = employees.filter((col("department") == dept) & (col("salary") >= min_salary))

    if filtered_df.count() > 0:
        filtered_df.show()
    else:
        print("No employees match these criteria.")

widgets.interact(filter_employees, dept=dept_dropdown, min_salary=salary_slider)

"""Final Mini Project

Using all datasets, generate report:

Top Employee

Average Salary

Department Employee Count

Total Sales

Best Sales Employee

Save results to:
final_report.txt
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, avg, count, desc


# --- Metric 1: Top Employee (Highest Salary) ---
top_emp_row = employees.orderBy(desc("salary")).first()
top_emp_name = top_emp_row["name"]
top_emp_salary = top_emp_row["salary"]

# --- Metric 2: Average Salary ---
avg_salary = employees.select(avg("salary")).collect()[0][0]

# --- Metric 3: Department Employee Count ---
# Filling null departments with "Unassigned" for the report
dept_counts = employees.fillna("Unassigned", subset=["department"]) \
                       .groupBy("department").count().collect()

# --- Metric 4: Total Sales ---
total_sales_val = sales.select(sum("amount")).collect()[0][0]

# --- Metric 5: Best Sales Employee (Highest Total Sales Amount) ---
best_sales_df = sales.groupBy("emp_id").agg(sum("amount").alias("total_sales")) \
                     .join(employees, "emp_id") \
                     .orderBy(desc("total_sales")).select("name", "total_sales").first()

best_sales_name = best_sales_df["name"]
best_sales_amount = best_sales_df["total_sales"]

# --- Generate the Report String ---
report_content = f"""--- FINAL MINI PROJECT REPORT ---
1. Top Employee (Highest Salary): {top_emp_name} (Rs. {top_emp_salary})
2. Average Salary: Rs. {avg_salary:.2f}
3. Total Sales: Rs. {total_sales_val}
4. Best Sales Employee: {best_sales_name} (Total Sales: Rs. {best_sales_amount})

5. Department-wise Employee Count:
"""

for row in dept_counts:
    report_content += f"   - {row['department']}: {row['count']}\n"

with open("final_report.txt", "w") as f:
    f.write(report_content)

print("Report generated successfully! Check final_report.txt.")