# -*- coding: utf-8 -*-
"""PySpark Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dch_7cd0uwQC-ML_uTq3vkOars93V0Pc
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("PySpark Basics") \
    .getOrCreate()

print("Spark Session Created")

spark.version

data = [
    ("Steve", 22, "Chennai"),
     ("Jerry", 25, "Bangalore")
]

columns = ["name", "age", "city"]

df = spark.createDataFrame(data, columns)

df.show()

df.printSchema()

df.select("Name").show()

df.select("Name", "Age").show()

df.filter(df.age>23).show()

df.groupBy("city").count().show()

df.orderBy("Age").show()

df.orderBy(df.age.desc()).show()