# -*- coding: utf-8 -*-
"""PySpark_DataBases.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Mkxr-TlhxkC9v3KScSS3cxCdZL4jZ7C
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("PySpark Basics") \
    .getOrCreate()

print("Spark Session Created")

data = [
    (1, "Rahul", "IT", 70000, "2024-01-10"),
    (2, "Sneha", "HR", 60000, "2024-02-15"),
    (3, "Arjun", "IT", 75000, "2024-03-01"),
    (4, "Priya", "Finance", 80000, "2024-01-25"),
    (5, "Karan", None, 50000, "2024-02-20")
]

columns = ["emp_id", "name", "department", "salary", "joining_date"]

df = spark.createDataFrame(data, columns)
df.show()

df.show()
df.printSchema()
df.columns
df.count()

df.columns

df.show(3)

df_renamed = df.withColumnRenamed("Salary", "Payment")
df_renamed.show()

df.filter(df.department == "IT").show()
df.filter((df.salary > 70000) & (df.department == "IT")).show()

df.drop("joining_date").show()

from pyspark.sql.functions import sum, avg, max, min

df.select(
    sum("salary").alias("Total salary"),
    avg("salary").alias("Average salary"),
    max("salary").alias("Max salary"),
    min("salary").alias("Mins salary")
).show()

dept_data = [
    ("IT", "Bangalore"),
    ("HR", "Mumbai"),
    ("Finance", "Delhi")
]

dept_columns = ["department", "location"]

dept_df = spark.createDataFrame(dept_data, dept_columns)
dept_df.show()

df.join(dept_df, on="department", how="inner").show()

df.join(dept_df, on="department", how="left").show()

df.join(dept_df, on="department", how="right").show()

df.withColumn("bonus", df.salary * 0.1).show()

df.show()

from pyspark.sql.functions import col

df.filter(col("department").isNull()).show()

df.na.fill({"department": "Unknown"}).show()

df.na.drop().show()

from pyspark.sql.functions import upper, lower, length

df.select(
    "name",
    upper("name").alias("upper name"),
    lower("name").alias("lower name"),
    length("name").alias("length of name")
).show()

from google.colab import files
uploaded = files.upload()

!ls

df = spark.read.csv("employees.csv", header=True, inferSchema=True)
df.show()